version: '2'

services:

  update-search:
    build:
        context: .
        dockerfile: ./Dockerfile-dev
    environment:
      - SOLR_URL=http://localhost:8983/solr/articles
      - LOGGING_LEVEL=DEBUG
      - DEBUG=True
    command: python updatesearch/metadata.py -c spa

  update-search-preprint:
    build:
        context: .
        dockerfile: ./Dockerfile-dev
    volumes:
      - .:/app
    environment:
      - SOLR_URL=http://localhost:8983/solr/articles
      - OAI_URL=https://preprints.scielo.org/index.php/scielo/oai
      - LOGGING_LEVEL=DEBUG
      - DEBUG=True
    command: python updatepreprint/updatepreprint.py -t 1
